language: python

sudo: false

dist: trusty

services:
  - postgresql

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: TEST_TARGET=default
  - python: 3.6
    env: TEST_TARGET=default
  - python: 2.7
    env: TEST_TARGET=cli
  - python: 2.7
    env: TEST_TARGET=build_cbi
  - python: 2.7
    env: TEST_TARGET=coding_standards
  allow_failures:
  - python: 3.6
    env: TEST_TARGET=default
  - python: 2.7
    env: TEST_TARGET=build_cbi
  - python: 2.7
    env: TEST_TARGET=coding_standards


before_install:
  - ./ci-helpers/postgres_setup.sh
  - wget http://bit.ly/miniconda -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update conda
  - conda config --set show_channel_urls true
  - conda config --add channels conda-forge --force
  - conda create -n TEST python=$TRAVIS_PYTHON_VERSION --file requirements.txt --file requirements-dev.txt
  - source activate TEST
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install configparser ;
    fi

# Test source distribution.
install:
  - python setup.py sdist && version=$(python setup.py --version) && pushd dist  && pip install WOFpy-${version}.tar.gz && popd

before_script:
  - python wof/examples/flask/swis/runserver_swis.py --config=./test/test_swis_config2.cfg --connection=sqlite:///./test/test_swis2.db &

script:
  - if [[ $TEST_TARGET == 'default' ]]; then
      py.test -s -rxs -v -k "not cbi" ;
    fi

  - if [[ $TEST_TARGET == 'build_cbi' ]]; then
      python wof/examples/flask/cbi/build_cbi_cache.py ;
      py.test -s -rxs -v -k "cbi" ;
    fi

  - if [[ $TEST_TARGET == 'cli' ]]; then
      pushd /tmp ;
      wofpy_config wofpyserver ;
      wofpy_config wofpyserver --mode=production --overwrite=soft ;
      wofpy_config wofpyserver -m production -o hard ;
      popd ;
    fi

  - if [[ $TEST_TARGET == 'coding_standards' ]]; then
      flake8 --max-line-length=105 wof ;
      flake8 --max-line-length=105 test ;
    fi
